### ISSUE TITLE
A question about pack.js

### ISSUE THREAD

**Issue by lucasmaffazioli** [samme/cavern-quest#11]
I mean... How do you import a folder like `import assets from './assets'`, and then access a png file like `assets.bomb` without even specifying the extension? I've never seen this, and is so useful, but I cannot make it work with Vite+TS.

Many thanks!!

**Comment by samme** [comment]
In Vite I believe you can do

```js
const files = import.meta.glob('../assets/*', { eager: true })

this.load.image('bomb', files['../assets/bomb.png'].default)
```

**Comment by lucasmaffazioli** [comment]
Thank you so much! Awesome :)
